# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0004_auto_20170805_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiccontent',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='dynamiccontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='dynamiccontenttranslation',
            name='master',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dynamic_content.DynamicContent'),
            preserve_default=False,
        ),
    ]
